# TODO: export this to midnight.nvim once finalized

########################## GENERAL #########################

[colors]

# terminal colors
ansi = [
    '#181818',
    '#fa4d56',
    '#42be65',
    '#c8b670',
    '#5080ff',
    '#a665d0',
    '#50b0e0',
    '#b5bdc5',
]
brights = [
    '#525252',
    '#ff7279',
    '#7ac098',
    '#f8e6a0',
    '#78a9ff',
    '#a3a0d8',
    '#9ac6e0',
    '#e0e0e0',
]

# general
foreground = '#b5bdc5'
background = '#080c10'
cursor_fg = '#080c10'
cursor_bg = '#b5bdc5'
cursor_border = '#b5bdc5'
scrollbar_thumb = '#212121'
selection_bg = '#012749'

# miscellaneous
split = '#393939'
compose_cursor = '#ff0000'

# TODO: Colors for copy_mode and quick_select
#
# -- available since: 20220807-113146-c2fee766
# -- In copy_mode, the color of the active text is:
# -- 1. copy_mode_active_highlight_* if additional text was selected using the mouse
# -- 2. selection_* otherwise
# copy_mode_active_highlight_bg = { Color = '#000000' },
# -- use `AnsiColor` to specify one of the ansi color palette values
# -- (index 0-15) using one of the names "Black", "Maroon", "Green",
# --  "Olive", "Navy", "Purple", "Teal", "Silver", "Grey", "Red", "Lime",
# -- "Yellow", "Blue", "Fuchsia", "Aqua" or "White".
# copy_mode_active_highlight_fg = { AnsiColor = 'Black' },
# copy_mode_inactive_highlight_bg = { Color = '#52ad70' },
# copy_mode_inactive_highlight_fg = { AnsiColor = 'White' },
#
# quick_select_label_bg = { Color = 'peru' },
# quick_select_label_fg = { Color = '#ffffff' },
# quick_select_match_bg = { AnsiColor = 'Navy' },
# quick_select_match_fg = { Color = '#ffffff' }

########################## TAB BAR #########################

[colors.tab_bar]
background = '#080c10'

[colors.tab_bar.active_tab]
fg_color = '#080c10'
bg_color = '#697077'
intensity = 'Bold'
underline = 'None'
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
fg_color = '#878d96'
bg_color = '#080c10'
intensity = 'Normal'
underline = 'None'
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
fg_color = '#878d96'
bg_color = '#212121'
intensity = 'Normal'
underline = 'None'
italic = false
strikethrough = false

[colors.tab_bar.new_tab]
fg_color = '#878d96'
bg_color = '#080c10'
intensity = 'Bold'
underline = 'None'
italic = false
strikethrough = false

[colors.tab_bar.new_tab_hover]
fg_color = '#878d96'
bg_color = '#212121'
intensity = 'Bold'
underline = 'None'
italic = false
strikethrough = false
